def add_copy_clear():
    print("-----------------ADD COPY CLEAR PART-------------------")
    a = set()
    a.add(55)
    print("a is ",a)
    a.clear()
    print("a is ",a)
    a.add(56)
    b = a.copy()
    print("a is ",a)
    print("-----------------ADD COPY CLEAR PART ENDS-------------------")
# add_copy_clear()
def diff():
    print("-----------------DIFF PART-------------------")
    c = a.difference(set())
    print("c is ",c)
    d_list = [55,56]
    d = set(d_list)
    print("a is ",a, "d is ",d)
    c = a.difference(d)
    print("c is ",c)
    c = d.difference(a)
    print("c is ",c)
    c = d.difference(set([54,56]))
    print("-----------------DIFF PART ENDS-------------------")
# diff()
def discard():
    print("-----------------DISCARD PART-------------------")
    c = set()
    print("c is ",c)
    c.add(920)
    c.add(56)
    c.add(56)
    print("c is ",c)
    c.discard(56)
    print("c is ",c)
    print("-----------------DISCARD PART ENDS-------------------")
# discard()
def discard1():
    print("-----------------DISCARD1 PART-------------------")
    c = set()
    print("c is ",c)
    c.add("920X")
    c.add("56Mill")
    c.add("56WEM")
    print("c is ",c)
    c.remove("55WEM")
    print("c is ",c)
    c.remove("55Meadows")
    print("c is ",c)
    print("-----------------DISCARD1 PART ENDS-------------------")
# discard1()


def popper():
    wem = [55,52,56,4,920]
    wem_set = set(wem)
    wem_set.add(900)
    while wem_set:
        print(wem_set.pop())
# popper()
